Mod- and UI- related stuff
Oxdeception/Corruption-of-Champions pull request #3
Opened 2019-01-04 08:21 UTC by aimozg

2019-01-09 23:06 UTC, Oxdeception requested changes
Please also add some form of background to the Module Menu, to make more easily read.
Could do this by allowing changes to the CoCScrollPane background alpha

2019-01-09 23:06 UTC, Oxdeception commented on content/coc/mountain/hellhound.xml
> +<command>Orgasm("Generic")</command>
```suggestion
<command>Orgasm(player, "Generic")</command>
```

2019-01-09 23:06 UTC, Oxdeception commented on content/coc/mountain/hellhound.xml
> +	<command>Orgasm("Generic")</command>
```suggestion
	<command>Orgasm(player, "Generic")</command>
```

2019-01-09 23:06 UTC, Oxdeception commented on classes/coc/xxc/StdFunctions.as
> +	public function CreatureHasTrait(creature:Creature,trait:String):Boolean {
Mod XML needs updating to account for change in parameters. Erlking/Goblin

2019-01-09 23:06 UTC, Oxdeception commented on classes/coc/xxc/StdFunctions.as
> -	public function CreatureTestSex(creature:Creature,sexTest:/*int*/Array):Boolean {
Need to update bundled mod XML's to account for this being removed.

2019-01-10 17:52 UTC, aimozg commented
My bad, missed some of Std(Commands/Functions) changes.
Fixed, also added simple validator (checks arg counter for simple commands and tests)

2019-01-11 20:05 UTC, aimozg commented
@Oxdeception All done

2019-01-14 22:09 UTC, merged